### ISSUE TITLE
TextMate now recommends /Library, not ~/Library

### ISSUE THREAD

**Issue by bitcababy** [handcrafted/handcrafted-haml-textmate-bundle#5]
Seems that everyone is cloning the same install instructions, which are out of date. The reason is, I believe, that ~/Library now contains personal changes to the official files.

**Comment by adamstac** [comment]
I haven't heard this. Can you link to an article or blog post detailing why the change? I searched Google, but came up with nothing.

**Comment by bitcababy** [comment]
It's in the manual.

Specifically:
When you have svn installed it is relatively easy to either checkout or export a bundle. TextMate searches for bundles in all the usual library locations, so if you have the rights to do so (on your machine) it is recommended that you perform all checkouts to /Library instead of ~/Library, since this then keeps installed bundles separate from custom bundles (or bundles you have edited).

**Comment by adamstac** [comment]
I would say that it would be up to the user to decide ~/Library or /Libray on that one - the same way you choose to sudo gem install or just gem install.

I'd prefer to install to ~/Library anyways because it's "my" stuff and it's a bundle I installed.

Thanks though. Good looking out.

**Comment by bitcababy** [comment]
The main reason to put a bundle into /Library rather than ~/Library is that ~/Library holds the changes you've made to the bundle; essentially a diff of the bundle you're running and the original bundle. So for anyone who is interested in raising an issue with a fix or contributing to a bundle in any other way, it's the best way to keep track of what you've changed.
